import React from 'react';

const PrivacyPolicy = () => {
  const sections = [
    {
      title: 'What Information Do We Collect?',
      content:
        'We collect information from you when you visit our website, register on our site, place an order, or fill out a form including your name, phone number, email address, and payment details.',
    },
    {
      title: 'When Does The Bot Agency Use Information From Third Parties?',
      content:
        'We may collect publicly available information and data shared through trusted third-party integrations to improve our services and customer experience.',
    },
    {
      title: 'Do We Share The Information We Collect With Third Parties?',
      content:
        'We do not sell your personal information. Information may only be shared with trusted service providers for operational and legal purposes.',
    },
    {
      title: 'How Do We Use The Information We Collect?',
      content:
        'We use collected information to personalize experiences, improve services, process transactions, provide customer support, and send updates.',
    },
    {
      title: 'How Do We Use Your Email Address?',
      content:
        'Your email address may be used to send updates, respond to inquiries, share service information, and provide customer support.',
    },
    {
      title: 'How Long Do We Keep Your Information?',
      content:
        'We retain your information only for as long as necessary to provide services, comply with legal obligations, and resolve disputes.',
    },
    {
      title: 'How Do We Protect Your Information?',
      content:
        'We implement appropriate technical and organizational security measures to protect your personal data from unauthorized access and misuse.',
    },
  ];
  const definitions = [
    {
      term: 'Cookie',
      desc: 'A small amount of data generated by a website and saved by your web browser. Used to identify your browser, provide analytics, and remember information about you.',
    },
    {
      term: 'Company',
      desc: 'The Bot Agency, responsible for your information under this Privacy Policy.',
    },
    {
      term: 'Country',
      desc: 'India, where The Bot Agency is based.',
    },
    {
      term: 'Customer',
      desc: 'The company, organization or person that signs up to use The Bot Agency Service.',
    },
    {
      term: 'Device',
      desc: 'Any internet connected device such as a phone, tablet, or computer.',
    },
    {
      term: 'IP Address',
      desc: 'A number assigned to every device connected to the Internet, usually assigned in geographic blocks.',
    },
    {
      term: 'Personal Data',
      desc: 'Any information that allows for identification or identifiability of a natural person.',
    },
  ];

  return (
    <div className="bg-slate-50 min-h-screen">
      

      {/* Privacy Policy Content */}
      <main
        id="privacy-policy"
        className="max-w-4xl mx-auto px-6 py-24  text-slate-800 leading-relaxed"
      >
        <div className="mb-10 border-b pb-8">
          <h1 className="text-4xl font-bold text-slate-900 mb-4">
            Privacy Policy
          </h1>
          <p className="text-lg text-slate-600">
            The Bot Agency is committed to protecting your privacy. Learn how
            we collect, use, and protect your information.
          </p>
        </div>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold mb-4 text-slate-900">
            Introduction
          </h2>
          <p className="mb-4">
            The Bot Agency ("we," "our," or "us") is committed to protecting
            your privacy. This Privacy Policy explains how your personal
            information is collected, used, and disclosed by The Bot Agency.
          </p>
          <p>
            By accessing or using our Service, you signify that you have read,
            understood, and agree to our collection, storage, use, and
            disclosure of your personal information as described in this Privacy
            Policy and our Terms of Service.
          </p>
        </section>

        <section className="mb-10 bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
          <h2 className="text-2xl font-semibold mb-6 text-slate-900">
            Definitions and Key Terms
          </h2>

          <dl className="grid gap-4">
            {definitions.map((item) => (
              <div
                key={item.term}
                className="border-b border-slate-200 pb-3 last:border-0"
              >
                <dt className="font-bold text-slate-900">{item.term}:</dt>
                <dd className="text-slate-700">{item.desc}</dd>
              </div>
            ))}
          </dl>
        </section>

        <section className="mb-10 space-y-5">
          {sections.map((section, index) => (
            <details
              key={index}
              className="group bg-white border border-slate-200 rounded-2xl px-6 py-5 shadow-sm"
            >
              <summary className="flex items-center justify-between cursor-pointer list-none">
                <h3 className="text-2xl font-semibold text-slate-900">
                  {section.title}
                </h3>

                <span className="text-blue-600 text-2xl transition-transform duration-300 group-open:rotate-180">
                  ⌄
                </span>
              </summary>

              <p className="mt-5 text-slate-700 leading-relaxed text-lg">
                {section.content}
              </p>
            </details>
          ))}
        </section>

        <footer id="contact" className="mt-12 pt-8 border-t border-slate-200">
          <h2 className="text-2xl font-semibold mb-4 text-slate-900">
            Contact Us
          </h2>

          <p className="mb-3">
            If you have any questions, reach out to us at:
          </p>

          <a
            href="mailto:harry@thebot.agency"
            className="text-blue-600 hover:underline font-medium"
          >
            harry@thebot.agency
          </a>
        </footer>
      </main>
    </div>
  );
};

export default PrivacyPolicy;
